  export const Provinces = [
  {"province": "Abra"},
  {"province": "Agusan Del Norte"},
  {"province": "Agusan Del Sur"},
  {"province": "Aklan"},
  {"province": "Albay"},
  {"province": "Antique"},
  {"province": "Apayao"},
  {"province": "Aurora"},
  {"province": "Basilan"},
  {"province": "Bataan"},
  {"province": "Batanes"},
  {"province": "Batangas"},
  {"province": "Benguet"},
  {"province": "Biliran"},
  {"province": "Bohol"},
  {"province": "Bukidnon"},
  {"province": "Bulacan"},
  {"province": "Cagayan"},
  {"province": "Camarines Norte"},
  {"province": "Camarines Sur"},
  {"province": "Camiguin"},
  {"province": "Capiz"},
  {"province": "Catanduanes"},
  {"province": "Cavite"},
  {"province": "Cebu"},
  {"province": "Compostela Valley"},
  {"province": "Cotabato"},
  {"province": "Davao Del Norte"},
  {"province": "Davao Del Sur"},
  {"province": "Davao Oriental"},
  {"province": "Eastern Samar"},
  {"province": "Guimares"},
  {"province": "Ifugao"},
  {"province": "Ilocos Norte"},
  {"province": "Ilocos Sur"},
  {"province": "Iloilo"},
  {"province": "Isabela"},
  {"province": "Kalinga"},
  {"province": "Laguna"},
  {"province": "Lanao Del Norte"},
  {"province": "Lanao Del Sur"},
  {"province": "La Union"},
  {"province": "Leyte"},
  {"province": "Maguindanao"},
  {"province": "Marinduque"},
  {"province": "Masbate"},
  {"province": "Metropolitan Manila"},
  {"province": "Misamis Occidental"},
  {"province": "Misamis Oriental"},
  {"province": "Mountain Province"},
  {"province": "Negros Occidental"},
  {"province": "Negros Oriental"},
  {"province": "Northern Samar"},
  {"province": "Nueva Ecija"},
  {"province": "Nueva Viscaya"},
  {"province": "Occidental Mindoro"},
  {"province": "Oriental Mindoro"},
  {"province": "Palawan"},
  {"province": "Pampanga"},
  {"province": "Pangasinan"},
  {"province": "Quezon"},
  {"province": "Quirino"},
  {"province": "Rizal"},
  {"province": "Romblon"},
  {"province": "Samar"},
  {"province": "Sarangani"},
  {"province": "Siquijor"},
  {"province": "Sorsogon"},
  {"province": "South Cotabato"},
  {"province": "Southern Leyte"},
  {"province": "Sultan Kudarat"},
  {"province": "Sulu"},
  {"province": "Surigao Del Norte"},
  {"province": "Surigao Del Sur"},
  {"province": "Tarlac"},
  {"province": "Tawi-Tawi"},
  {"province": "Zambales"},
  {"province": "Zamboanga Del Norte"},
  {"province": "Zamboanga Del Sur"},
  {"province": "Zamboanga-Sibugay"},
  {"province": "Dinagat Islands"},
]
